### PR TITLE
Added certs and key for grafana

### PR DESCRIPTION
**Pull request by jbasu01**
@computate please review

### CODE REVIEW

**Comment by schwesig** [comment]
@schwesig

**Comment by computate** [comment]
Nice @jbasu01 , we should test this out on Monday, and remove the comments in the code.

**Comment by jbasu01** [comment]
Sounds good @computate  . By the way, it was a joint effort between Thor and myself.

**Comment by schwesig** [comment]
https://github.com/nerc-project/operations/issues/326

comment from Lars
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/317#issuecomment-1841674363

**Review by computate — APPROVED** [review]

**Comment by computate** [comment]
@jbasu01 looks good! If you believe this is ready to merge, please remove the "WIP" in the title.

**Review by schwesig — APPROVED** [review]
looking good

**Comment by computate** [comment]
Excellent work @jbasu01 @schwesig @harshil-codes , I see the grafana metrics working with the new observatorium data source applied!

**Comment by schwesig** [comment]
Thanks, Yes, we just checked it after the merge 👍🙏

**Pull request merged**
