### PR TITLE
Add ClusterSecretStore to nerc-ocp-obs cluster

### PR DESCRIPTION
**Pull request by larsks**
- Removed namespaced secretstores from nerc-ocp-obs cluster
- Add ClusterSecretStore to nerc-ocp-obs cluster

### CODE REVIEW

**Comment by larsks** [comment]
Converted to draft because I think a couple of the externalsecrets may need to be updated...

**Review by computate — APPROVED** [review]

**Comment by larsks** [comment]
Should be all set now.

**Comment by schwesig** [comment]
> Should be all set now.

@larsks one of the quickests drafts I know of :-)
I call you Lucky Lars Luke now...

**Review by schwesig — APPROVED** [review]
quick fix by deep knowledge, thanks

**Comment by schwesig** [comment]
https://github.com/nerc-project/operations/issues/280

**Pull request merged**
