### PR TITLE
Adding dex oauth authentication to grafana.

### PR DESCRIPTION
**Pull request by computate**
See the documentation here: 
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/

### CODE REVIEW

**Review by dystewart — APPROVED** [review]

**Review by naved001 — APPROVED** [review]

**Comment by joachimweyl** [comment]
@computate is this ready for merge?

**Comment by computate** [comment]
@joachimweyl not yet, this will require additional changes after #80 is approved and merged

**Comment by joachimweyl** [comment]
@computate the [Patch Operator PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/80) is merged. What changes need to be made to this PR to merge it?

**Comment by dystewart** [comment]
@joachimweyl @computate with the patch operator merged we'll need to add a couple of things, namely a serviceAccount (in the docs the default one is used but since we need to add permissions I think we should create a dedicated sa), rbac adding perms to allow patching in the desired namespace, and the runtime patch. 
The docs aren't specific about what permissions the serviceaccount needs and they just give is cluster-admin with the explanation: "#shortcut to get all permissions, we are not testing permissions, but the actual patching capability" 
I have gotten a working runtime patch in a dev cluster where I patch a secret field into another resource just as we need to do here but I still need to find out what perms the serviceaccount actually needs to function since granting cluster-admin is unnecessary and bad practice. I should have an update on this later this afternoon.

**Comment by dystewart** [comment]
It seems the only resource the serviceaccount mentioned above needs access to is the tokenrequest api. I will make a PR adding all the necessary changes tomorrow

**Comment by larsks** [comment]
@dystewart Have you made the pr you mentioned [earlier](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/75#issuecomment-1247411141)? I guess link it here when it's ready so that we can coordinate our merges...

**Comment by dystewart** [comment]
@larsks Here is the PR [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/82](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/82)

**Comment by larsks** [comment]
@computate  @dystewart  is this ready to go now that #82 has merged?

**Comment by computate** [comment]
Yes @larsks

**Pull request merged**
