### PR TITLE
Add Secretstore for openshift-logging in test cluster

### PR DESCRIPTION
**Pull request by bnshr**
This add the secretstore for test cluster required for openshift-logging

### CODE REVIEW

**Comment by computate** [comment]
@bnshr Looks like we should also update the `nerc-ocp-config/cluster-scope/overlays/nerc-ocp-test/secretstores/kustomization.yaml` as well.

**Comment by bnshr** [comment]
Done!

**Review by computate — APPROVED** [review]

**Review by schwesig — APPROVED** [review]
thumbs up

**Comment by computate** [comment]
@larsks could you please grant vault access to this SecretStore in the `openshift-logging` namespace in the `test` cluster?

**Comment by larsks** [comment]
@computate I can (and I [have](https://github.com/OCP-on-NERC/vault-config/commit/ddd4985a707bce4d581b8a47c1073a083bc601c4)), but now we have a second problem: the test cluster doesn't have valid certificates, which will prevent it from accessing the vault.

I've opened https://github.com/nerc-project/operations/issues/424 on this topic.

**Comment by larsks** [comment]
@computate External secrets on the test cluster are now syncing correctly...

```
NAMESPACE               NAME                                               STORE               REFRESH INTERVAL   STATUS              READY
curator-system          postgres-config                                    nerc-secret-store   1h                 SecretSyncedError   False
group-sync-operator     github-group-sync                                  nerc-secret-store   1h                 SecretSynced        True
koku-metrics-operator   postgres-config                                    nerc-secret-store   1h                 SecretSynced        True
openshift-config        github-client-secret                               nerc-secret-store   1m                 SecretSynced        True
openshift-logging       openshift-logging-lokistack-gateway-bearer-token   nerc-secret-store   15s                SecretSynced        True
openshift-storage       rook-ceph-external-cluster-details                 nerc-secret-store   1h                 SecretSynced        True
```

...well, except for the one in `curator-system`, but that's a config error in that namespace.

**Comment by computate** [comment]
Thanks very much @larsks .

**Pull request merged**
