### PR TITLE
Adding namespace and cluster for obs

### LINKED ISSUE #280: Create basic configuration for observability cluster
Create basic configuration (auth, certificates, secrets, etc) for observability cluster.

- [ ] auth
- [ ] certificates
- [ ] secrets
- [ ] etc

### PR DESCRIPTION
**Pull request by schwesig**
fixes https://github.com/nerc-project/operations/issues/280
acm overlay & namespace  added for nerc-ocp-obs

### CODE REVIEW

**Comment by schwesig** [comment]
reason for draft:
need input for decisison if the addition in `cluster-scope/overlays/nerc-ocp-obs/` should be part of this PR as second commit or a new PR to separate connecting and configuration
@larsks @computate

**Review by computate — APPROVED** [review]

**Comment by computate** [comment]
Seems fine for the initial commit for `obs` in ACM before adding ArgoCD resources.

**Review by larsks — APPROVED** [review]

**Comment by larsks** [comment]
> need input for decisison if the addition in cluster-scope/overlays/nerc-ocp-obs/

Smaller, focused pull requests are easier to review!

**Comment by larsks** [comment]
I would recommend updating the commit message to reference nerc-project/operations#280 (just like you've done in the PR description). Someone running `git log` only sees commit messages, not PR descriptions.

**Comment by schwesig** [comment]
> I would recommend updating the commit message to reference [nerc-project/operations#280](https://github.com/nerc-project/operations/issues/280) (just like you've done in the PR description). Someone running `git log` only sees commit messages, not PR descriptions.

Thanks, done that.

**Pull request merged**
