### PR TITLE
moving all cluster-scoped manifests out of loki application directory

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Signed-off-by: greg pereira <grpereir@redhat.com>

following discussion in MOC Slack: https://massopencloud.slack.com/archives/C027TDE52TZ/p1666623728336859

### CODE REVIEW

**Review by dystewart — APPROVED** [review]

**Review by naved001 — CHANGES_REQUESTED** [review]
Thanks @Gregory-Pereira for organizing this! I think we'll need to update the overlay for nerc-ocp-infra to include the 4 things that are now under `cluster-scope/base/` otherwise this change would break the loki deployment that's currently running on nerc-ocp-infra.

**Comment by joachimweyl** [comment]
> we'll need to update the overlay for nerc-ocp-infra to include the 4 things that are now under `cluster-scope/base/` otherwise this change would break the loki deployment that's currently running on nerc-ocp-infra.

@naved001 will this require an additional PR or were you suggesting including it in this PR?

**Comment by naved001** [comment]
@joachimweyl those changes need to be together otherwise it'll break things, so it needs to be part of this PR. We could push a commit to this PR, or close this and submit another PR.

**Comment by joachimweyl** [comment]
> We could push a commit to this PR, or close this and submit another PR.

@Gregory-Pereira can you make the requested updates to this PR?

**Comment by naved001** [comment]
We'll get to it at some point later. For now, I am going to close this PR.

**Pull request closed without merging**
